// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TypeScriptCompileOnSave
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCompilePackageString = "92479255-4cce-4754-9caa-a0c47a10e055";
        public const string guidAutoLoadString = "92479255-4cde-4751-9cba-a0c47a10e056";
        public const string guidCompilePackageCmdSetString = "e062e925-6e86-483e-95e7-fddfca31f177";
        public static Guid guidCompilePackage = new Guid(guidCompilePackageString);
        public static Guid guidAutoLoad = new Guid(guidAutoLoadString);
        public static Guid guidCompilePackageCmdSet = new Guid(guidCompilePackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int AddConfigFileId = 0x0100;
    }
}
